configure amazon self hosted

diff --git a/.github/workflows/imagepush.yml b/.github/workflows/imagepush.yml
--- a/.github/workflows/imagepush.yml
+++ b/.github/workflows/imagepush.yml
@@ -2,7 +2,7 @@
 name: Docker Image Build and Push
 
 on:
- workflow_call:
+  workflow_call:
 
 jobs:
   image_push:
@@ -11,10 +11,25 @@ jobs:
       DOCKER_IMAGE: tobadocker12/petapp:${{ github.sha }}
 
     steps:
+      - name: Ensure Docker is Installed and Running
+        run: |
+          if ! command -v docker &> /dev/null; then
+            echo "Docker not found. Installing..."
+            sudo yum update -y
+            sudo yum install -y docker.io
+            sudo systemctl start docker
+            sudo systemctl enable docker
+            sudo usermod -aG docker $USER
+          else
+            echo "Docker is already installed."
+          fi
+          sudo systemctl restart docker
+          docker --version
+
       - name: Build Docker Image
         run: |
-          sudo docker build -t ${{ env.DOCKER_IMAGE }} .
-          sudo docker save ${{ env.DOCKER_IMAGE }} > docker_image.tar
+          docker build -t $DOCKER_IMAGE .
+          docker save $DOCKER_IMAGE > docker_image.tar
 
       - name: Upload Docker Image Artifact
         uses: actions/upload-artifact@v3
@@ -23,7 +38,7 @@ jobs:
           path: docker_image.tar
 
       - name: Log in to DockerHub
-        run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
       - name: Push Docker Image
-        run: sudo docker push ${{ env.DOCKER_IMAGE }}
+        run: docker push $DOCKER_IMAGE
