configure amazon self hosted

diff --git a/.github/workflows/javabuild.yml b/.github/workflows/javabuild.yml
--- a/.github/workflows/javabuild.yml
+++ b/.github/workflows/javabuild.yml
@@ -1,10 +1,7 @@
-
-
-# .github/workflows/build.yml
 name: Build
 
 on: 
- workflow_call:
+  workflow_call:
 
 jobs:
   build:
@@ -25,6 +22,8 @@ jobs:
         with:
           path: ~/.m2/repository
           key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+          restore-keys: |
+            ${{ runner.os }}-maven-
 
       - name: Build with Maven
         run: mvn clean install
@@ -34,15 +33,18 @@ jobs:
         with:
           name: jar
           path: target/*.jar
+
       - name: Configure JFrog CLI
         uses: jfrog/setup-jfrog-cli@v3
         with:
-            version: latest
+          version: latest
         env:
-            JF_URL: https://trialuz45a9.jfrog.io/artifactory/DevSecOps-JF/
-            JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}
+          JF_URL: https://trialuz45a9.jfrog.io/artifactory/DevSecOps-JF/
+          JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}
 
-      - name: Upload Artifact to JFrog (use wildcard for all jars)
+      - name: Upload Artifact to JFrog
         run: |
-          jf rt u "target/*.jar" "DevSecOps-JF/"
-    
+          if ! jf rt u "target/*.jar" "DevSecOps-JF/"; then
+            echo "Failed to upload artifacts to JFrog"
+            exit 1
+          fi
